ironArray/Caterva2

README.md, tests/supervisor.conf
The commands used to start the different processes in the Supervisor configuration in tests work just fine with plain sh, so there is no need to require Bash.
Similarly, the examples in the readme are simple enough to not require Bash either, so refer to the former in the Markdown fenced block.
=> Use plain sh instead of Bash

src/sub.py, src/utils.py
The features are:
- Get item with unpack sequence syntax for the slice (`array[*slice]`), maybe supported after the adoption of the specializing interpreter (PEP 659).  Use the (uglier) `array.__getitem__(*slice)` instead.
- The `asyncio.timeout()` context manager.  Use `asyncio.await_for()` instead.
Alternatively, the minimum Python version of the package may be bumped from the 3.8 declared in `pyproject.toml` to 3.11, but that would discard some distro versions.
=> Avoid features that require Python >= 3.11

.gitignore, README.md, tests/conftest.py, tests/supervisor.conf
This enhances test code with the following features:
- Use `root-example` as data for tests, unless there is a `tests/data` directory (either empty or with data files).
- All variable state from tests is confined to the `tests/var` directory (if you want to reuse your current one, just move it there). It is kept between test executions, but there is a variable `tests.conftest.services():purge_var` which may be toggled to experiment with cleaning up the directory before tests.
- The test Supervisor is always stopped, even on errors.
- The test Supervisor keeps individual programs' logs under `tests/var/supervisor-logs`.
- Last but not least, before running tests there is a polling check (with a timeout) for every program run by Supervisor to reach the `RUNNING` status. Its configuration …
=> Enhance tests for data examples and process control

README.md, SPECS.md, src/models.py, src/sub.py, src/utils.py
This fixes some issues:
* Use the `blocks` and `blocksize` when creating the metadata on `.b2nd` and `.b2frame` cache files respectively.  This is important so that the ingestion of chunks in the subscriber works properly; in particular, the `show` command works now when using datasets with several blocks per chunk.
* `.b2frame` files are filled with `UNINIT` values now.
* The tutorial section in README has been enhanced to include the `show` command.  Also, some more TODOs have been placed or refined.
=> Some fixes in show command and metadata in cache files

tests/conftest.py, tests/supervisor.conf, tests/test_cli.py
This is intended to ease the adoption of tests that modify data files. Where data files where previously expected at `tests/data` and it was symlinked to `root-example` if missing, here the latter is copied as `tests/caterva2/data`.
Additionally, tests can be invoked no matter where like `pytest -v SOURCE_DIR`, though test variable data dir remains `SOURCE_DIR/tests/caterva2`. This may be a start for supporting creating the `caterva2` directory elsewhere or in the current directory.
=> Copy example root into variable test data directory

SPECS.md, caterva2/api.py, caterva2/api_utils.py, caterva2/clients/cli.py, caterva2/services/sub.py, caterva2/tests/test_api.py
This PR removes the partial downloads feature.  Partial downloads can have different bad effects:
1) They need a second re-compression to get the relevant slice of the data.  When using lossy codecs, this may lead to further and undesired loss of quality.
2) They require special management on the subscriber (e.g. a new downloads/ directory).
By removing this capability, we avoid these issues.
As a bonus, this PR provides an additional decompression step for the regular files when the `blosc2` package is present on the client side (it is currently optional).
=> No partial downloads

caterva2/api.py, caterva2/api_utils.py, caterva2/services/sub.py, caterva2/tests/test_api.py
This adds a new `fetch` API for the HTTP methods.  This is to make intentions more clear, and to simplify the code too.
Also, a new serialization method based on Blosc2 can be used in the communications between the subscriber and the client.  It is active by default if Blosc2 is installed. In comparison with the previous pickle, the new method allows to reduce the bandwidth when a lot of data is to be transferred.  Some tweaking could be used when the length of the data would be too small; then pickle should always win.
=> New fetch API for better separation of concerns

README.md, SPECS.md, caterva2.sample.toml, caterva2/clients/cli.py, caterva2/clients/tbrowser.py, caterva2/services/bro.py, caterva2/services/pub.py, caterva2/services/srv_utils.py, caterva2/services/sub.py, caterva2/tests/conf.py, caterva2/tests/conftest.py, caterva2/tests/services.py, caterva2/tests/test_api.py, caterva2/tests/test_cli.py, caterva2/utils.py, pyproject.toml
This adds support for a `$PWD/caterva2.toml` configuration file as mentioned in the specs. Any service or client program may look up its own configuration in there, or the configuration of other programs (e.g. to know their service endpoint). Settings in the configuration file may be overridden by command line options and arguments; this has been achieved by using configuration settings as defaults for `argparse`. Also, some programs allow an `--id` option to support having multiple programs of the same category share the configuration file (as per specs).
Tests have been adapted to handle the presence of a configuration file at the current directory (to some extent), and an example configuration file has been added.
Both the example and the handling of such file by tests may need further …
=> Basic configuration file support

.github/workflows/python-app.yml, README-DEVELOPERS.md, README.md, RELEASING.rst, caterva2/__init__.py, caterva2/tests/__init__.py, caterva2/tests/__main__.py, doc/getting_started/installation.rst, pyproject.toml
Installing the plain Caterva2 wheel with no extras may result in tests failing, since the dependencies for services and clients are not installed. This means that the only use of the pytest main dependency was to allow the `caterva2.test` function to not break importing `caterva2`, unless one also installed the services and clients extras, something which was not indicated in documentation when referring to tests.
This PR creates an explicit tests extra that depends on the services and clients extras plus pytest (dependency moved here). It is used in CI actions and the documentation has been fixed to mention it, so that tests do work.
~~Invocations of the `caterva2.test` function (now `caterva2.tests.main`) have been replaced with invocations to the more standard `pytest --pyargs …
=> Add extra feature for tests

caterva2/services/sub.py, caterva2/tests/test_api.py
This undoes the root being part of datasets in clients (e.g. for listing operations).  One of the issues is when the subscriber is subscribed to more than one root; in this case, listings are merging datasets belonging to different roots.  This PR fixes this.
For what is worth, the actual `urlpath` is still accessible for the user in the metadata view:
=> Undo root being part of dataset path in clients

caterva2/tools/cat2_to_hdf5.py, caterva2/tools/common.py, caterva2/tools/hdf5_to_cat2.py
This updates `cat2export` and (especially) `cat2import` to respect compression parameters found in Blosc2-compressed datasets (native or in HDF5).
`cat2import` is now able to retrieve parameters from the schunk in a Blosc2-compressed HDF5 dataset, or use default ones for other datasets. In any case, it iterates over chunks one by one, and converts them on-the-fly only if necessary (Blosc2 chunks are copied literally without further processing). That means that at most one chunk is in memory for a converted dataset.
`cat2export` also implements similar techniques for chunk-by-chunk processing (for arrays and frames, although plain files are still slurped and compressed). When creating an HDF5 dataset, default Blosc2 compression parameters are used for plain files, and similar filter …
=> Carry compression params on import/export

caterva2/services/pub.py, caterva2/services/pubroot.py, caterva2/services/srv_utils.py
This PR places an abstraction layer in front of root/dataset access at the publisher, so that operations on the root or its datasets follow an interface defined in the `caterva2.servicess.pubroot.PubRoot` abstract base class.
The implementation for the usual directory-based root now constitutes the `DirectoryRoot` class in the same module.
This should hopefully help adding other root implementations like HDF5 or Zip files.
=> Use publisher root classes

caterva2/hdf5.py, caterva2/services/hdf5root.py, caterva2/tools/hdf5_to_cat2.py
This extends the work in #28 with on-the-fly translation of attributes in HDF5 datasets. The msgpacked attributes are cached for efficiency. Preliminary tests have been performed with basic attributes like strings, but the machinery may need extra work for other attribute types (as is the case with `cat2import`, which now shares code with this).
=> Convert dataset attributes to Blosc2 vlmeta in HDF5 publisher root

caterva2/hdf5.py, caterva2/tools/hdf5_to_cat2.py, pyproject.toml
This continues #28 by fixing the way vlmeta values are imported from HDF5 to (i) be again compatible with Blosc2's tuple handling (as the old behaviour was buggy), (ii) transform NumPy values into native Python before encoding for greater portability, and (iii) handle empty HDF5 values.
The dependency on msgpack has been moved to the correct location after refactoring HDF5 publisher root and HDF5 import code.
=> Fix HDF5 msgpack handling

caterva2/services/sub.py, caterva2/services/templates/info.html, pyproject.toml, root-example/README.md
This adds support for displaying a markdown file. It doesn't depend on the `contenttype`, rather if the original file is a "md", an html is always created with the contents of the markdown files when the user clicks on `Display`.
=> Add support for displaying md files

caterva2/services/srv_utils.py
This fixes two issues with the creation of Blosc2 datasets (e.g. in cache files at the subscriber):
1. The `contiguous` attribute being copied from the original when creating a frame dataset file. Just let the default storage be used when creating the dataset locally, as non-contiguous datasets are not properly supported by the publisher (which opens the inner `chunks.b2nd` and crashes), and its value may not be meaningful for virtual datasets (e.g. those dynamically generated by the HDF5 root publisher). (The default was correctly used in array dataset creation.)
2. The `cparams` attribute not being propagated from the original when creating an array dataset file. Although individual chunks kept their parameters, the super-chunk always got default ones.
Some minor refactoring has been …
=> Fix init_b2 arguments for array/schunk creation

README.md, caterva2/api.py, caterva2/api_utils.py, caterva2/services/static/main.js, caterva2/services/sub.py, caterva2/services/subscriber/db.py, caterva2/services/subscriber/schemas.py, caterva2/services/subscriber/users.py, caterva2/services/templates/home.html, caterva2/services/templates/login.html, caterva2/services/templates/logout.html, caterva2/services/templates/register.html, caterva2/tests/services.py, pyproject.toml
This adds experimental FastAPI Users-based machinery to require user authentication for API and Web client operations. User registration is possible (without mail verification yet). Authentication tokens are transported with cookies, since that is easier for web browser usage, the primary target of this initial implementation. See the readme for more information.
Please note that this is only intended for demo and experimentation support, and many user management features are still missing. Also, the API client implementation does not yet support authentication at all.
=> Experimental user authentication support

SPECS.md, caterva2.sample.toml, caterva2/__init__.py, caterva2/api.py, caterva2/api_utils.py, caterva2/clients/cli.py, caterva2/clients/tbrowser.py, caterva2/services/sub.py, caterva2/tests/services.py, caterva2/tests/sub_auth.py, caterva2/tests/test_api.py, caterva2/tests/test_cli.py, caterva2/tests/test_hdf5root.py, caterva2/utils.py, doc/reference/top_level.rst, doc/tutorials/API.md, doc/tutorials/cli.md, doc/tutorials/independent-services.md, doc/utilities/cat2cli.md, examples/query_subscriber.py
This allows to provide the subscriber with the URL to be used as a base for its public service. For instance, a subscriber behind a reverse proxy may listen on `localhost:8002` (`subscriber.http`) but be accessible in `https://cat2.example.com/` (`subscriber.url`). The latter is used in API and web client responses that need to include complete, public subscriber URLs, thus fixing the issue that a subscriber behind a reverse proxy could either provide a working web client or a working API, but not both.
The `--host` option in clients (`HOST:PORT`, default to `subscriber.http`) has been replaced by the `--subscriber` option (URL base, default to `subscriber.url`), with docs and tests updated.
=> Support subscriber URL base in configuration

caterva2/__init__.py, caterva2/api.py, caterva2/api_utils.py, caterva2/clients/cli.py, caterva2/clients/tbrowser.py, caterva2/tests/sub_auth.py, caterva2/tests/test_api.py, caterva2/tests/test_cli.py, caterva2/tests/test_hdf5root.py, doc/reference/top_level.rst, doc/tutorials/independent-services.md, doc/utilities/cat2cli.md, examples/query_subscriber.py
This makes the names used in code for subscriber URL bases and dataset paths consistent with those used in Blosc2:
- `sub_url` becomes either `sub_urlbase` (in contexts where several kinds of services may be mentioned) or just `urlbase` (when clearly applying to a subscriber).
- `dataset` and its "name" become `path` in the API.
=> Urlbase renames for consistency

caterva2/services/plugins/tomography/__init__.py, caterva2/services/sub.py
This extends contenttype handling to check against a function that looks at dataset metadata if it can be categorized as some known contenttype, but only if the dataset does not explicitly provide one in its vlmeta. The function can be customized with specific functions coming from plugin modules.
Support is included to detect tomographies automatically, as long as they match those against which display code has been tested (greyscale and RGB(A) ones).
=> Tomography detection

caterva2/services/plugins/tomography/__init__.py, caterva2/services/sub.py
This simplifies the changes in #45 with more understandable names and simpler operation for detecting the content type of a dataset. The detection function in a plugin does just say whether the dataset looks like having the content type implemented by the plugin or not, and there's no need to explicitly register it once the plugin has already been registered.
The plugin's guessing function also gets the dataset path in case it may be useful. For instance, Markdown display machinery could be implemented as a plugin with this (though that is a topic for another PR).
Inspired by <https://github.com/zakirullin/cognitive-load> via @FrancescAlted.
=> Content type detection simplifications

caterva2/__init__.py, caterva2/api.py, caterva2/models.py, caterva2/services/sub.py, caterva2/tests/test_api.py, doc/reference/top_level.rst, doc/tutorials/API.md
This adds an `/api/lazyexpr/` endpoint to the subscriber API where an expression may be POSTed to create a new lazy expression dataset under scratch space, much as it was already possible via the web client. In fact, they both share the same underlying code now.
It also adds some extra checks that were missing in the original lazyexpr creation code.
A top-level client API function has been added, as well as tests and a short section in the API tutorial.
=> Lazy expression subscriber API

caterva2/api_utils.py, caterva2/services/plugins/tomography/__init__.py, caterva2/services/srv_utils.py, caterva2/services/sub.py, caterva2/services/subscriber/db.py, caterva2/services/subscriber/users.py, caterva2/tests/sub_auth.py
To properly run this branch, the wheel from the `CacheSChunk` branch in python-blosc2 must be installed.
This PR adds the usage of the class blosc2.ProxySChunk. 
With these changes, every published dataset will be treated as a ProxySChunk. To access its data the partial_download func must be called to first initialize the cache.
When the files are in scratch, such as uploaded files or LazyExpr files, they are treated like a blosc2.SChunk or blosc2.NDarray instead.
=> Add usage of blosc2.ProxySChunk

Makefile, caterva2/api_utils.py, caterva2/services/bro.py, caterva2/services/pub.py, caterva2/services/sub.py, caterva2/utils.py
It works except for websockets, because these are not supported by fastapi_websocket_pubsub / fastapi_websocket_rpc 
c.f. https://github.com/permitio/fastapi_websocket_rpc/issues/41
This means that the publishers and subscribers can listen to unix sockets, but not yet the broker.
=> Support for Unix Domain Sockets (wip)

caterva2/services/srv_utils.py, caterva2/services/sub.py
With this, evaluations work with operands in @shared:
and the outcome:
Fixes #62
=> Make evaluations work with arrays in @shared

caterva2/services/srv_utils.py, caterva2/services/sub.py, caterva2/services/templates/path_list.html
With this, filesizes are viewed as: 
Perhaps we can stretch the view a bit more, but I am unsure whether this can affect other things.
Fixes #60
=> Make the size of the file to fit comfortably in dataset view

caterva2/__init__.py, caterva2/api.py, caterva2/services/sub.py, caterva2/tests/test_api.py
This PR removes the 'NotImplementedError' from `get_chunk` when the dataset is a LazyExpr.
=> Support get_chunk for LazyExpr

caterva2/services/sub.py
It has occurred to me that supporting uploading and automatic extraction of tarballs or zipfiles would be a cool way to allow the creation of hierarchies in `@shared` (and `@scratch` too).  I'm still not sure how to deal with the redirection part (it is possible to point to a directory, or better use the first path in the tarball?).
Fixes #64.
=> Support for uploading tar (tar.gz and .tgz are also in) and zipfiles.

caterva2/__init__.py, caterva2/api.py, caterva2/api_utils.py, caterva2/clients/cli.py, caterva2/services/sub.py, caterva2/tests/services.py, caterva2/tests/test_api.py
This implements a `remove()` API.  Note that I used `remove` noun instead of `delete` (used in the `htmx` interface) because it seems to me that the former is more usual when removing files in filesystems (e.g. `os.remove()`, `os.rmdir()` or `shutil.rmtree()`).
=> remove() api

caterva2/models.py, caterva2/services/sub.py, caterva2/services/templates/includes/info_metadata.html
Right now, the cparams are not propagated properly to caterva2. This may fix the problem.
=> Add CParams property to proxy source

caterva2/api.py, caterva2/tests/test_api.py
For Dataset class (which inherits from File class), can now access certain meta-information directly. Test added which checks that the relevant attributes for Dataset instances are correct (but skips File instances).
=> Added shape, dtype, blocks and chunks to Dataset class

caterva2/api_utils.py
``fetch_data`` used to run
```
data = response.content
#Try different deserialization methods
try:
data = blosc2.ndarray_from_cframe(data)
data=data[:] if data.ndim==1 else data[()]
except RuntimeError:
data = blosc2.schunk_from_cframe(data)
data=data[:] 
```
which caused an uninformative error to be thrown in the except block if the second line in the try block failed (since data was no longer a bytes object). This has been changed to allow a more informative error to be thrown. In addition, changed indexing signature so that data[()] is used only on 0d arrays.
=> Change exception handling in api_utils.fetch_data

caterva2/__init__.py, caterva2/api_utils.py, caterva2/client.py, caterva2/tests/test_api.py, doc/reference/client_class.rst, doc/reference/dataset_class.rst, doc/reference/file_class.rst, doc/reference/root_class.rst, examples/get-slice.py
This allows to receive a native `NDArray` or `SChunk`  right in the client, without any conversion.
=> Add a new Dataset.slice() method

caterva2/client.py, caterva2/tests/test_api.py, doc/tutorials/API.md
Previously reurned None if Dataset.meta did not have attribute. This causes an error to be thrown for shpare, blocks and chunks since `tuple(None)` fails. Now throws more informative AttributeError.
=> Improved exception handling for Dataset attributes

caterva2/client.py, caterva2/tests/test_api.py
Fixes #156. Client.fetch accepted strings for the slice_ argument from the user (different to behaviour of File/Dataset, which accepted slice instances). This has been altered so that all three accept slice instances.
In addition, minor fix to exception handling in Dataset, recommended by ruff.
=> Change behaviour of Client.fetch to accept slice not str

caterva2/client.py, caterva2/tests/test_api.py, doc/reference/dataset_class.rst, doc/reference/file_class.rst
=> Simplify API: remove File.fetch() as it duplicates File.__getitem__()

doc/tutorials/index.md, doc/tutorials/web-client.md
Reword some parts of docs and fix main error which was inconsistency between image and text in "Computing expressions on datasets" section. Also reorder tutorials so that easier stuff (web client and API) comes first.
=> Fix errors in docs

caterva2/client.py, caterva2/models.py, caterva2/services/sub.py, caterva2/tests/test_api.py
Allows one to send lazyexprs such as ``linspace(0, 10)`` to the server without specifying a dummy argument. Fixes #170. 
In order for this to be useful, added the ability to force execution of the sent lazyexpr server-side.
=> Make operands arg optional for lazyexprs

caterva2/services/sub.py
Small bug for case where slice_ = 0, which returned whole array (i.e. ()) not just first element.
=> Fix indexing bug

caterva2/services/srv_utils.py, caterva2/tests/test_api.py
Rather than internal representation of lazyexpr (used for calculation), display the original string expression and operands, which will be more familiar to the user.
=> Make lazyexpr metadata more readable

caterva2/api_utils.py, caterva2/client.py, caterva2/tests/test_api.py, examples/Video4-LazyExprs_Using_Notebooks.ipynb
Improve coverage of Timeout errors for fetch_data and add explicit error message at level of Caterva2 to guide users to increase timeout limit for Client instance.
=> Adding explicit Timeout error for informing users

caterva2/services/sub.py, caterva2/tests/test_api.py
Due to incorrect mode argument, could not concatenate more than two arrays. This is now fixed.
=> Fix concatenate for more than two arrays

Makefile, SPECS.md, caterva2.sample.toml, caterva2/client.py, caterva2/clients/cli.py, caterva2/clients/tbrowser.py, caterva2/services/plugins/tomography/__init__.py, caterva2/services/settings.py, caterva2/services/srv_utils.py, caterva2/services/sub.py, caterva2/tests/services.py, caterva2/tools/adduser.py, caterva2/utils.py, examples/Caterva2Video.ipynb, examples/lazyexpr-chained.py
Code review/cleanup and change server's default port to 8000
This is a follow up of PR #232
=> Code review/cleanup and change server's default port to 8000

README-DEVELOPERS.md, README.md, RELEASE_NOTES.md, SPECS.md, caterva2.sample.toml, caterva2/client.py, caterva2/clients/cli.py, caterva2/services/settings.py, caterva2/tests/services.py, doc/tutorials/cli.md, doc/tutorials/configuration.md, doc/tutorials/independent-services.md, doc/tutorials/launching-services.md, examples/query_server.py, pyproject.toml
Most of the references to the previous publish-subscriber are gone now, and replaced by client-server paradigm.  We still need to decide what to do with the `independent-services.md` tutorial.
=> Subscriber to server
